services:
  comfyui:
    build:
      context: .
      dockerfile: Dockerfile
    image: "yanwk/comfyui-boot:cpu"
    init: true
    container_name: comfyui-cpu
    expose:
      - "8188"
    volumes:
      - ./storage:/root
      - ./storage-models/models:/root/ComfyUI/models
      - ./storage-models/hf-hub:/root/.cache/huggingface/hub
      - ./storage-models/torch-hub:/root/.cache/torch/hub
      - ./storage-user/input:/root/ComfyUI/input
      - ./storage-user/output:/root/ComfyUI/output
      - ./storage-user/workflows:/root/ComfyUI/user/default/workflows
    environment:
      - CLI_ARGS="--cpu"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.comfyui.entrypoints=web,websecure"
      - "traefik.http.routers.comfyui.rule=Host(`comfyui.martin-linde.com`)"
      - "traefik.http.services.comfyui.loadbalancer.server.port=8188"
      - "traefik.http.routers.comfyui.tls.certresolver=letsencrypt"
